#!/usr/bin/env node

import {
  createCLI,
  definePlugin,
  definePrompt,
  defineTemplate,
  validators,
  type UITheme
} from '../src/index';

// Example of creating a custom plugin
const customTheme = {
  primary: '#ff6b6b',
  secondary: '#4ecdc4',
  success: '#45b7d1',
  error: '#f9ca24',
  warning: '#f0932b',
  info: '#eb4d4b',
  muted: '#6c5ce7'
} satisfies UITheme;

const myCustomPlugin = definePlugin({
  name: 'my-custom-plugin',
  version: '1.0.0',
  description: 'A custom plugin example',
  hooks: {
    beforeGenerate: async (config) => {
      console.log(`🔌 Plugin: Starting generation for ${config.projectName}`);
    },
    afterGenerate: async (config, projectPath) => {
      console.log(`🔌 Plugin: Finished generating ${config.projectName} at ${projectPath}`);
    },
    beforeInstall: async (projectPath) => {
      console.log(`🔌 Plugin: About to install dependencies in ${projectPath}`);
    },
    afterInstall: async (projectPath) => {
      console.log(`🔌 Plugin: Dependencies installed in ${projectPath}`);
    },
    onError: async (error, context) => {
      console.error(`🔌 Plugin: Error in ${context}:`, error.message);
    }
  },
  templates: [
    defineTemplate({
      name: 'custom-react',
      description: 'Custom React template with extra features',
      files: [
        {
          path: 'README.md',
          content: (answers) => `# ${answers.projectName}

This is a custom React project created with my plugin!

## Features
- Custom styling
- Enhanced development experience
- Plugin-powered generation

## Getting Started

\`\`\`bash
npm install
npm run dev
\`\`\`
`
        },
        {
          path: 'src/custom-component.tsx',
          content: (answers) => `import React from 'react';

interface CustomComponentProps {
  title: string;
}

export const CustomComponent: React.FC<CustomComponentProps> = ({ title }) => {
  return (
    <div style={{
      padding: '20px',
      background: 'linear-gradient(45deg, #ff6b6b, #4ecdc4)',
      borderRadius: '8px',
      color: 'white',
      textAlign: 'center'
    }}>
      <h2>{title}</h2>
      <p>This component was generated by a custom plugin!</p>
    </div>
  );
};
`
        }
      ],
      dependencies: {
        production: {
          'react': '^18.2.0',
          'react-dom': '^18.2.0'
        },
        development: {
          '@vitejs/plugin-react': '^4.2.1',
          'vite': '^5.0.0',
          'typescript': '^5.0.0',
          '@types/react': '^18.2.0',
          '@types/react-dom': '^18.2.0'
        }
      },
      scripts: {
        'dev': 'vite',
        'build': 'vite build',
        'preview': 'vite preview'
      },
      postInstall: async (projectPath, answers) => {
        console.log(`🎉 Custom plugin setup complete for ${answers.projectName}!`);
      }
    })
  ],
  validators: {
    customProjectName: {
      validate: (value: string) => {
        if (value.includes('plugin')) {
          return 'Project name cannot contain "plugin" when using this custom plugin';
        }
        return true;
      },
      message: 'Custom validation failed'
    }
  },
  themes: {
    custom: customTheme
  }
});

// Define prompts
const prompts = [
  definePrompt({
    name: 'projectName',
    type: 'input',
    message: '📁 Project name',
    validate: validators.projectName
  }),
  definePrompt({
    name: 'template',
    type: 'select',
    message: '🎨 Choose a template',
    choices: [
      { name: 'Custom React (Plugin)', value: 'custom-react', description: 'React with custom plugin features' },
      { name: 'Standard React', value: 'react', description: 'Standard React setup' }
    ]
  }),
  definePrompt({
    name: 'useCustomTheme',
    type: 'confirm',
    message: '🎨 Use custom theme?',
    default: true
  }),
  definePrompt({
    name: 'installDeps',
    type: 'confirm',
    message: '📦 Install dependencies?',
    default: true
  })
];

// Standard React template
const reactTemplate = defineTemplate({
  name: 'react',
  description: 'Standard React + Vite + TypeScript',
  files: [
    {
      path: 'src/App.tsx',
      content: (answers) => `import { useState } from 'react'

function App() {
  const [count, setCount] = useState(0)

  return (
    <div className="App">
      <h1>Welcome to ${answers.projectName}</h1>
      <div className="card">
        <button onClick={() => setCount((count) => count + 1)}>
          count is {count}
        </button>
      </div>
    </div>
  )
}

export default App`
    }
  ],
  dependencies: {
    production: {
      'react': '^18.2.0',
      'react-dom': '^18.2.0'
    },
    development: {
      '@vitejs/plugin-react': '^4.2.1',
      'vite': '^5.0.0',
      'typescript': '^5.0.0'
    }
  }
});

// Create CLI with plugin
const cli = createCLI({
  name: 'plugin-example-cli',
  version: '1.0.0',
  description: 'CLI with custom plugin example',
  prompts,
  templates: [reactTemplate],
  plugins: [myCustomPlugin],
  theme: customTheme,
  allowModeSelection: true
});

cli.parse();
